# Generated by Django 4.1.7 on 2023-03-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0009_alter_categoryroom_category_coefficient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryroom',
            name='category_coefficient',
        ),
        migrations.RemoveField(
            model_name='categoryroom',
            name='price_modification',
        ),
        migrations.AddField(
            model_name='room',
            name='price_1person',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='price_2person',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='price_3person',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='price_pets',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
