# Generated by Django 4.1.7 on 2023-03-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0010_remove_categoryroom_category_coefficient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='price_comment',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
