# Generated by Django 4.1.7 on 2023-03-16 22:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0011_room_price_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Помилка в номері телефону', regex='^\\+?3?8?0\\d{2}[- ]?(\\d[- ]?){7}$')]),
        ),
        migrations.AlterField(
            model_name='roomphoto',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_photo', to='main_page.room'),
        ),
    ]
