# Generated by Django 4.1.7 on 2023-03-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0013_reservation_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='room_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user_email',
            field=models.CharField(default='12345@gmail.com', max_length=100),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user_id',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room_id',
            field=models.IntegerField(),
        ),
    ]
